import {
  siCelery,
  siClaude,
  siCypress,
  siDjango,
  siDocker,
  siExpress,
  siFirebase,
  siGit,
  siGithubactions,
  siGooglebigquery,
  siGooglecloud,
  siHetzner,
  siJest,
  siJquery,
  siLaravel,
  siLeaflet,
  siModelcontextprotocol,
  siMqtt,
  siMysql,
  siNeon,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siPandas,
  siPhp,
  siPostgresql,
  siPrisma,
  siPython,
  siReact,
  siReactquery,
  siRedis,
  siRedux,
  siSap,
  siSass,
  siStripe,
  siTailwindcss,
  siTypescript,
  siVite,
  siVitest,
  siZod,
} from "simple-icons";

// Stack names used in Info.jsx → Simple Icons. Names without an entry are not rendered.
const techIcons = {
  "Node.js": siNodedotjs,
  Express: siExpress,
  TypeScript: siTypescript,
  React: siReact,
  Redux: siRedux,
  "TanStack Query": siReactquery,
  Stripe: siStripe,
  BigQuery: siGooglebigquery,
  Jest: siJest,
  Vitest: siVitest,
  Claude: siClaude,
  MCP: siModelcontextprotocol,
  GCP: siGooglecloud,
  Docker: siDocker,
  Laravel: siLaravel,
  MySQL: siMysql,
  Sass: siSass,
  PHP: siPhp,
  jQuery: siJquery,
  SAP: siSap,
  Vite: siVite,
  PostgreSQL: siPostgresql,
  Prisma: siPrisma,
  Zod: siZod,
  Firebase: siFirebase,
  "Next.js": siNextdotjs,
  Tailwind: siTailwindcss,
  Leaflet: siLeaflet,
  Python: siPython,
  Django: siDjango,
  Redis: siRedis,
  Celery: siCelery,
  MQTT: siMqtt,
  "GitHub Actions": siGithubactions,
  Nginx: siNginx,
  Hetzner: siHetzner,
  Git: siGit,
  Cypress: siCypress,
  Neon: siNeon,
  pandas: siPandas,
};

export const getTechIcon = (name) => techIcons[name];

export const TechIcon = ({ icon, ...props }) => (
  <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" {...props}>
    <path d={icon.path} />
  </svg>
);
